#!/bin/sh

condor_vacate box11.cims.nyu.edu
condor_vacate c1.cs.nyu.edu
condor_vacate c10.cs.nyu.edu
condor_vacate c11.cs.nyu.edu
condor_vacate c12.cs.nyu.edu
condor_vacate c13.cs.nyu.edu
condor_vacate c14.cs.nyu.edu
condor_vacate c15.cs.nyu.edu
condor_vacate c16.cs.nyu.edu
condor_vacate c17.cs.nyu.edu
condor_vacate c2.cs.nyu.edu
condor_vacate c3.cs.nyu.edu
condor_vacate c4.cs.nyu.edu
condor_vacate c5.cs.nyu.edu
condor_vacate c6.cs.nyu.edu
condor_vacate c7.cs.nyu.edu
condor_vacate c8.cs.nyu.edu
condor_vacate c9.cs.nyu.edu
condor_vacate crunchy2.cims.nyu.edu
condor_vacate csstupc53.cs.nyu.edu
condor_vacate euler08.cims.nyu.edu
condor_vacate m1.cs.nyu.edu
condor_vacate s1.cs.nyu.edu
condor_vacate int1.cims.nyu.edu
condor_vacate int2.cims.nyu.edu
condor_vacate int3.cims.nyu.edu
condor_vacate int4.cims.nyu.edu

sleep 5

condor_vacate box11.cims.nyu.edu
condor_vacate c1.cs.nyu.edu
condor_vacate c10.cs.nyu.edu
condor_vacate c11.cs.nyu.edu
condor_vacate c12.cs.nyu.edu
condor_vacate c13.cs.nyu.edu
condor_vacate c14.cs.nyu.edu
condor_vacate c15.cs.nyu.edu
condor_vacate c16.cs.nyu.edu
condor_vacate c17.cs.nyu.edu
condor_vacate c2.cs.nyu.edu
condor_vacate c3.cs.nyu.edu
condor_vacate c4.cs.nyu.edu
condor_vacate c5.cs.nyu.edu
condor_vacate c6.cs.nyu.edu
condor_vacate c7.cs.nyu.edu
condor_vacate c8.cs.nyu.edu
condor_vacate c9.cs.nyu.edu
condor_vacate crunchy2.cims.nyu.edu
condor_vacate csstupc53.cs.nyu.edu
condor_vacate euler08.cims.nyu.edu
condor_vacate m1.cs.nyu.edu
condor_vacate s1.cs.nyu.edu
condor_vacate int1.cims.nyu.edu
condor_vacate int2.cims.nyu.edu
condor_vacate int3.cims.nyu.edu
condor_vacate int4.cims.nyu.edu
